### ISSUE TITLE
automatic installation doesn't pick up dependencies in setup.py

### ISSUE THREAD

**Issue by dmalt** [neuropycon/ephypype#21]
In setup.py we do import of ephipype  to get a version of the package,
which breaks the installation if the dependencies of ephipype haven't been installed manually beforehand.

**Comment by annapasca** [comment]
Hi Dima, about installation I think we have to install by pip, is it @davidmeunier79 @jasmainak @EtienneCmb ?

**Comment by dmalt** [comment]
@annapasca, you mean without cloning it from github like this
```
pip install ephipype
```
?

**Comment by annapasca** [comment]
In the neuropycon channel of slack I read David tried to create a package for graphpype

**Comment by dmalt** [comment]
Hi, @annapasca! What I'm trying to say is that when installing ephypype with pip
the requirements from the install_requires list should be installed automatically but it doesn't happen
because we import ephypype package first. This is part of [setup.py](https://github.com/neuropycon/ephypype/blob/master/setup.py): 
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Setup configuration."""

from setuptools import setup, find_packages
import ephypype

VERSION = ephypype.__version__

if __name__ == "__main__":
    setup(...)
```
It's easy to fix by commenting out the ```import ephypype``` line but I'm not sure what to do with the VERSION.

**Comment by davidmeunier79** [comment]
Yes there is a self referencing loop here that does not appear to be normal... For graphpype the version needs to be set by hands, but do not involve a previous round install. Maybe you can suppress both import and VERSION and set the version by hand at the moment?

**Comment by dmalt** [comment]
@davidmeunier79, ok, I'll go with that.

**Comment by davidmeunier79** [comment]
Can you let me know once it is done? I will try to post a version on pip repo after that

**Comment by davidmeunier79** [comment]
I have done a packaging of the current version of ephypype (no problem with the version for me...) . Can someone have a try at a pip install ephypype?

Should be version ephypype-0.1.dev0

https://pypi.org/project/ephypype/

**Comment by dmalt** [comment]
I just tried to install ephypype in a clean environment with ```pip install ephypype``` and the installation went fine.
When I tried to import ephypype though it complained about  missing the matplotlib package which is caused by mne. But here the problem is not on our side I think.

**Comment by dmalt** [comment]
@davidmeunier79 I just pushed a new setup.py if it's still relevant.

**Comment by annapasca** [comment]
@dmalt can you make a PR to merge the setup? Furthermore can you insert

`install_requires=['mne>=0.16',`

thks!

**Comment by dmalt** [comment]
Ok!

**Comment by dmalt** [comment]
Pull request is there: https://github.com/neuropycon/ephypype/pull/23

**Comment by davidmeunier79** [comment]
done

**Comment by jasmainak** [comment]
agreed there was a bug. 

But the pull request still does not fix the issue
